name: Scala Steward

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  pull-requests: write

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }} # Required to use gh cli
  VERSION: "${{ github.run_number }}-${{ github.run_attempt }}"
jobs:

  PostBuild:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ env.VERSION }}
    steps:

      - name: check files
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/search/repositories?q=topic:scala-steward+org:cborticigd" | jq -r '.items[].full_name | "- \(.)"' > REPOSITORIES.md
          ls -l
          cat REPOSITORIES.md
      
      - uses: scala-steward-org/scala-steward-action@v2.75.0
        with:
          github-token: ${{ secrets.TOKEN }}
          repos-file: REPOSITORIES.md
          author-email: scala-steward@users.noreply.github.com
          author-name: Scala Steward
